openapi: "3.0.0"

info:
  title: "Science Classifier"
  description: "API that accepts a text string predicts whether it is science content."
  version: "10.0"

paths:
  /SciencePredictor:
    post:
      description: "Classify a text string"

      requestBody:
        description: "Json with single field containing text to extract entities from"
        required: true
        content:
          application/json: {}

      responses:
        '200':
          description: "Returns a prediction and a probability"
          content:
           application/json: {}
